#include "Shape.h"

int Rectangle::calculateArea()
{
    return length * width;
}

int Triangle::calculateArea()
{
    //return 0; //autogenerated "stub function definition" 

    return (1.0 / 2) * base * height; 
}
